name: connection_manager
description: A simple connection manager to work with API and network calls
version: 1.2.1
homepage: "https://github.com/mobilesoftcode/connection_manager"
issue_tracker: "https://github.com/mobilesoftcode/connection_manager/issues"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cookie_jar: ^4.0.8
  dio: ^5.3.2
  dio_cookie_manager: ^3.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  graphql_flutter: ^5.1.2
  html_unescape: ^2.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=2.0.2 <4.0.0"
  bloc_test: ^9.1.5

flutter:

  assets:
    - assets/
    - mocks/